apiVersion: apps/v1
kind: Deployment
metadata:
  name: accent-detector
  labels:
    app: accent-detector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accent-detector
  template:
    metadata:
      labels:
        app: accent-detector
    spec:
      containers:
      - name: accent-detector
        image: yourusername/accent-detector:latest
        ports:
        - containerPort: 8501
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: accent-detector-secrets
              key: openai-api-key
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: accent-detector-service
spec:
  selector:
    app: accent-detector
  ports:
  - port: 80
    targetPort: 8501
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: accent-detector-secrets
type: Opaque
data:
  openai-api-key: BASE64_ENCODED_API_KEY  # Replace with: echo -n "your_api_key" | base64
